# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'stripe_ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for stripe_ios
  pod 'SwiftyJSON'
  pod 'Stripe'

end

target 'stripeIntegration' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for stripeIntegration

  target 'stripeIntegrationTests' do
    # Pods for testing
  end

end
